[2024-06-01T03:45:53.517+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_bigquery_2.check_file_exists manual__2024-06-01T03:45:30.694934+00:00 [queued]>
[2024-06-01T03:45:53.590+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_bigquery_2.check_file_exists manual__2024-06-01T03:45:30.694934+00:00 [queued]>
[2024-06-01T03:45:53.594+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-06-01T03:45:53.676+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): check_file_exists> on 2024-06-01 03:45:30.694934+00:00
[2024-06-01T03:45:53.728+0000] {standard_task_runner.py:60} INFO - Started process 3005 to run task
[2024-06-01T03:45:53.754+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'csv_to_bigquery_2', 'check_file_exists', 'manual__2024-06-01T03:45:30.694934+00:00', '--job-id', '443', '--raw', '--subdir', 'DAGS_FOLDER/csv_to_bigquery_2.py', '--cfg-path', '/tmp/tmpgz0pi_p_']
[2024-06-01T03:45:53.787+0000] {standard_task_runner.py:88} INFO - Job 443: Subtask check_file_exists
[2024-06-01T03:45:54.051+0000] {task_command.py:423} INFO - Running <TaskInstance: csv_to_bigquery_2.check_file_exists manual__2024-06-01T03:45:30.694934+00:00 [running]> on host 6204b7e2d2f9
[2024-06-01T03:45:54.513+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_bigquery_2' AIRFLOW_CTX_TASK_ID='check_file_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T03:45:30.694934+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-01T03:45:30.694934+00:00'
[2024-06-01T03:45:54.596+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-06-01T03:45:54.612+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-06-01T03:45:54.614+0000] {gcs.py:249} INFO - Getting list of the files. Bucket: testing_bucket_df12; Delimiter: None; Prefix(es): network_data/hello_1.csv
[2024-06-01T03:45:58.425+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-06-01T03:45:58.456+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=csv_to_bigquery_2, task_id=check_file_exists, execution_date=20240601T034530, start_date=20240601T034553, end_date=20240601T034558
[2024-06-01T03:45:58.525+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-06-01T03:45:58.597+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
